apiVersion: v1                    # Версия Kubernetes API
kind: Pod                         # Тип ресурса   
metadata:                         # Метаданные объекта
  name: my-pod-nginx              # Имя Pod
  namespace: default              # Пространство имен
  labels:                         # Метки для идентификации и селекции  
    app: nginx                    # Метка для приложения
spec:                             # Спецификация Pod, Настройки Pod
  restartPolicy: Always           # Политика перезапуска контейнеров в Pod (Always, OnFailure, Never)
  containers:                     # Список контейнеров в Pod
    - name: nginx                 # Имя контейнера
      image: nginx:1.23           # Docker-образ для контейнера (nginx версии 1.23)
      ports:                      # Список портов, которые контейнер будет слушать
        - containerPort: 80       # Порт внутри контейнера, который будет открыт
      env:                        # Список переменных окружения для контейнера
        - name: ENVIRONMENT       # Имя переменной окружения
          value: "production"     # Значение переменной окружения
      resources:                  # Ресурсы, запрашиваемые и ограниченные для контейнера
        requests:                 # Запрашиваемые ресурсы (минимальные гарантированные ресурсы)
          cpu: "100m"             # Запрос на 100 миллиядеров CPU (0.1 CPU)
          memory: "128Mi"         # Ограниченные ресурсы (максимальные ресурсы, которые контейнер может использовать)
        limits:                   # Лимиты ресурсов
          cpu: "500m"             # Лимит на 500 миллиядеров CPU (0.5 CPU)
          memory: "256Mi"         # Лимит на 256 МиБ памяти
      livenessProbe:              # Настройки проверки живости контейнера
        httpGet:                  # Метод проверки (HTTP GET запрос)
          path: /                 # Путь для проверки
          port: 80                # Параметры проверки
        initialDelaySeconds: 15   # Время в секундах, которое Kubernetes будет ждать перед первой проверкой живости после запуска контейнера
        periodSeconds: 20         # Интервал в секундах между проверками живости
      readinessProbe:             # Настройки проверки готовности контейнера
        httpGet:                  # Метод проверки (HTTP GET запрос)
          path: /                 # Путь для проверки
          port: 80                # Параметры проверки
        initialDelaySeconds: 5    # Время в секундах, которое Kubernetes будет ждать перед первой проверкой готовности после запуска контейнера
        periodSeconds: 10         # Интервал в секундах между проверками готовности
  volumes:                        # Список томов, которые будут доступны для контейнеров в Pod
    - name: tmp-storage           # Имя тома
      emptyDir: {}                # Тип тома (emptyDir - временное хранилище, которое создается при запуске Pod и удаляется при его удалении)

